Algoritmo "operações aritiméticas"
// Autor(a)    : rafael
// Data atual  : 23/06/2021
Var
// Seção de Declarações das variáveis
   valor1, valor2, valor3, resultado: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
   valor1 := 10
   valor2 := 10
   valor3 := 10
   
   resultado := ((valor1+valor2+valor3)/valor3)%2
   escreval("Resultado: ", resultado)

Fimalgoritmo